image_data_array = [ 
["acanthosis nigricans$similar lesions on neck$_other.jpg","acanthosis nigricans","other","similar lesions on neck"],
["acanthosis nigricans_1other.jpg","acanthosis nigricans","other","No hint"],
["acanthosis nigricans_other.jpg","acanthosis nigricans","other","No hint"],
["accessory nipple_other.jpg","accessory nipple","other","No hint"],
["acne conglobata_inflam.jpg","acne conglobata","infl","No hint"],
["acquired perforating dermatosis$on dialysis$_other.jpg","acquired perforating dermatosis","other","on dialysis"],
["acroangiodermatitis in the setting of venous stasis (pseudo-Kaposi sarcoma)$not Kaposi's sarcoma$_infl.jpg","acroangiodermatitis in the setting of venous stasis (pseudo-Kaposi sarcoma)","infl","not Kaposi's sarcoma"],
["acrodermatitis enteropathica$confluent parakeratosis, epidermal pallor$_b_other.png","acrodermatitis enteropathica","other","confluent parakeratosis, epidermal pallor"],
["acrodermatitis enteropathica$SLC39A4 gene$_b_other.png","acrodermatitis enteropathica","other","SLC39A4 gene"],
["adenoma sebaceum in tuberous sclerosis_gene.jpg","adenoma sebaceum in tuberous sclerosis","gene","No hint"],
["allergic contact dermatitis_1infl.jpg","allergic contact dermatitis","infl","No hint"],
["allergic contact dermatitis_2infl.jpg","allergic contact dermatitis","infl","No hint"],
["allergic contact dermatitis_infl.jpg","allergic contact dermatitis","infl","No hint"],
["alopecia areata$common$_infl.jpg","alopecia areata","infl","common"],
["alopecia areata$white hairs$_infl.jpg","alopecia areata","infl","white hairs"],
["alopecia, scale, black dots in tinea capitis$infectious$_infx.png","alopecia, scale, black dots in tinea capitis","infx","infectious"],
["androgenetic alopecia_other.jpg","androgenetic alopecia","other","No hint"],
["angiokeratomas in Fabry's disease$lysosomal storage disease$_gene.jpg","angiokeratomas in Fabry's disease","gene","lysosomal storage disease"],
["angiokeratomas$purple dots, no need for clear focus$_neo.jpg","angiokeratomas","neo","purple dots, no need for clear focus"],
["angiosarcoma$so purple$_neo.jpg","angiosarcoma","neo","so purple"],
["angiosarcoma_neo.jpg","angiosarcoma","neo","No hint"],
["angular cheilitis_other.jpg","angular cheilitis","other","No hint"],
["ash leaf spot and Shagreen patch (collagenoma) in tuberous sclerosis complex$AD$_gene.png","ash leaf spot and Shagreen patch (collagenoma) in tuberous sclerosis complex","gene","AD"],
["atopic dermatitis_infl.jpg","atopic dermatitis","infl","No hint"],
["attached tick$a feast$_infx.jpg","attached tick","infx","a feast"],
["basal cell carcinoma_neo.jpg","basal cell carcinoma","neo","No hint"],
["basal cell carcinoma__neo.jpg","basal cell carcinoma","neo","No hint"],
["Becker nevus_neo.jpg","Becker nevus","neo","No hint"],
["Behcet's disease$not infectious$_infl.jpg","Behcet's disease","infl","not infectious"],
["Behcet's disease$not neoplastic or infectious$_infl.jpg","Behcet's disease","infl","not neoplastic or infectious"],
["black hairy tongue$bacterial overgrowth with causes including smoking, xerostomia (dry mouth), soft diet, poor oral hygiene, and antibiotic use$_other.jpg","black hairy tongue","other","bacterial overgrowth with causes including smoking, xerostomia (dry mouth), soft diet, poor oral hygiene, and antibiotic use"],
["blue nevus$melanocytic$_neo.jpg","blue nevus","neo","melanocytic"],
["blue nevus$Tyndall$_neo.jpg","blue nevus","neo","Tyndall"],
["bowenoid papulosis_neo.jpg","bowenoid papulosis","neo","No hint"],
["bullous arthropod_infx.jpg","bullous arthropod","infx","No hint"],
["bullous pemphigoid_1_infl.jpg","bullous pemphigoid","infl","No hint"],
["bullous pemphigoid_infl.jpg","bullous pemphigoid","infl","No hint"],
["cafe au lait macules_neo.jpg","cafe au lait macules","neo","No hint"],
["candidiasis$no hint for you$_infx","candidiasis","infx","no hint for you"],
["carbuncle$bacterial$_infx.jpg","carbuncle","infx","bacterial"],
["chillbains$cold exposure$_other.jpg","chillbains","other","cold exposure"],
["chromhidrosis$this is red sweat$_gene.jpg","chromhidrosis","gene","this is red sweat"],
["condyloma accuminata$viral$_1infx.jpg","condyloma accuminata","infx","viral"],
["condyloma accuminata$viral$_2infx.jpg","condyloma accuminata","infx","viral"],
["condyloma accuminata$viral$_infx.jpg","condyloma accuminata","infx","viral"],
["condyloma accuminata_infx.jpg","condyloma accuminata","infx","No hint"],
["confluent morbilliform drug eruption_other.jpg","confluent morbilliform drug eruption","other","No hint"],
["congenital nevus_neo.jpg","congenital nevus","neo","No hint"],
["crusted scabies_infx.jpg","crusted scabies","infx","No hint"],
["cutis verticis gyrata_other.jpg","cutis verticis gyrata","other","No hint"],
["Darier disease$autosomal dominant$_gene.jpg","Darier disease","gene","autosomal dominant"],
["Darier disease$autosomal dominant$__gene.jpg","Darier disease","gene","autosomal dominant"],
["dermal melanosis_neo.jpg","dermal melanosis","neo","No hint"],
["dermatofibroma$benign$_other.jpg","dermatofibroma","other","benign"],
["desktop.ini","desktop.ini","","No hint"],
["desmoplastic trichoepithelioma$paisley$_neo.png","desmoplastic trichoepithelioma","neo","paisley"],
["discoid lupus erythematosus$scarring process commonly located on scalps$_1_infl.jpg","discoid lupus erythematosus","infl","scarring process commonly located on scalps"],
["discoid lupus erythematosus$scarring process commonly located on scalps$_infl.jpg","discoid lupus erythematosus","infl","scarring process commonly located on scalps"],
["discoid lupus erythematosus$scarring$_infl.jpg","discoid lupus erythematosus","infl","scarring"],
["discoid lupus erythematosus$slowly expanding scarring plaques$_infl.jpg","discoid lupus erythematosus","infl","slowly expanding scarring plaques"],
["discoid lupus_infl.jpg","discoid lupus","infl","No hint"],
["drug exanthem$not infectious$_other.jpg","drug exanthem","other","not infectious"],
["ecchymosis from chronic topical steroid use$chronically self-treating$_other.jpg","ecchymosis from chronic topical steroid use","other","chronically self-treating"],
["eczematoid purpura of Doucas-Kapetanakis$a type of PPD, also known as eczematoid purpura$_infl.jpg","eczematoid purpura of Doucas-Kapetanakis","infl","a type of PPD, also known as eczematoid purpura"],
["Ehlers-Danlos_gene.jpg","Ehlers-Danlos","gene","No hint"],
["eosinophilic cellulitis_$steroid-responsive$infl.jpg.png","eosinophilic cellulitis","infl","steroid-responsive"],
["eosinophilic cellulitis_infl.jpg","eosinophilic cellulitis","infl","No hint"],
["epidermal nevus$congenital$_neo.jpg","epidermal nevus","neo","congenital"],
["epidermolysis bullosa$new and very old lesions present$_gene.jpg","epidermolysis bullosa","gene","new and very old lesions present"],
["epidermolysis bullosa_gene.jpg","epidermolysis bullosa","gene","No hint"],
["erosio digitalis blastomycetica$long name for candidiasis of web spaces$_infx.jpg","erosio digitalis blastomycetica","infx","long name for candidiasis of web spaces"],
["eruptive xanthomas in type IV familial hyperlipidemia (also seen in diabetes)$elevated triglycerides$_b_gene","eruptive xanthomas in type IV familial hyperlipidemia (also seen in diabetes)","gene","elevated triglycerides"],
["eruptive xanthomas_b_gene.png","eruptive xanthomas","gene","No hint"],
["erythema annulare centrifugum_inflam.jpg","erythema annulare centrifugum","infl","No hint"],
["erythema multiforme$not bug bites$_infl.jpg","erythema multiforme","infl","not bug bites"],
["erythema multiforme_infl.jpg","erythema multiforme","infl","No hint"],
["erythroplasia of Queyrat$neoplastic$_neo.jpg","erythroplasia of Queyrat","neo","neoplastic"],
["exanthem (from drug)$iatrogenic$_other.jpg","exanthem (from drug)","other","iatrogenic"],
["extragenital lichen sclerosus$more common on the vulva$_infl.jpg","extragenital lichen sclerosus","infl","more common on the vulva"],
["favus$Trichophyton$_infx.jpg","favus","infx","Trichophyton"],
["filiform wart$viral$_b_infx.jpg","filiform wart","infx","viral"],
["filiform wart$viral$_infx.jpg","filiform wart","infx","viral"],
["fixed drug eruption$medication-related$_infl.jpg","fixed drug eruption","infl","medication-related"],
["fixed drug eruption_other.jpg","fixed drug eruption","other","No hint"],
["flea bites (near sockline, often at ankles)$bite from a particular insect$_infx.jpg","flea bites (near sockline, often at ankles)","infx","bite from a particular insect"],
["geographic tongue (benign migratory glossitis)$loss of epithelium, particularly of the filiform papillae$_infl.png","geographic tongue (benign migratory glossitis)","infl","loss of epithelium, particularly of the filiform papillae"],
["giant congenital nevus_1_neo.jpg","giant congenital nevus","neo","No hint"],
["giant congenital nevus_neo.jpg","giant congenital nevus","neo","No hint"],
["gonococcal urethritis_infx.jpg","gonococcal urethritis","infx","No hint"],
["granuloma annulare$granulomatous$_infl.jpg","granuloma annulare","infl","granulomatous"],
["granuloma annulare$left dorsal hand with characteristic lesion$_infl.jpg","granuloma annulare","infl","left dorsal hand with characteristic lesion"],
["granuloma annulare$no need to treat in most cases$_infl.jpg","granuloma annulare","infl","no need to treat in most cases"],
["granuloma annulare_infl.jpg","granuloma annulare","infl","No hint"],
["green nail syndrome (chloronychia) from Pseudomonas$bacterial$_infx.jpg","green nail syndrome (chloronychia) from Pseudomonas","infx","bacterial"],
["guttate psoriasis with Koebnerization$scratched$_infl.jpg","guttate psoriasis with Koebnerization","infl","scratched"],
["guttate psoriasis$recent strep throat$_infl.jpg","guttate psoriasis","infl","recent strep throat"],
["habit tic deformity from onychotillomania_other.jpg","habit tic deformity from onychotillomania","other","No hint"],
["Hailey-Hailey$(familial benign chronic pemphigus, adult-onset, often in skin folds)$_gene.jpg","Hailey-Hailey","gene","(familial benign chronic pemphigus, adult-onset, often in skin folds)"],
["hand dermatitis (otherwise unspecified)$common$_infl.jpg","hand dermatitis (otherwise unspecified)","infl","common"],
["hand foot and mouth disease$viral$_infx.jpg","hand foot and mouth disease","infx","viral"],
["herpes simplex$don't blame dyshidrosis for these$_infx.jpg","herpes simplex","infx","don't blame dyshidrosis for these"],
["herpes simplex_infx.jpg","herpes simplex","infx","No hint"],
["herpes simplex__infx.jpg","herpes simplex","infx","No hint"],
["herpes zoster$viral$_infx.jpg","herpes zoster","infx","viral"],
["herpes zoster_1_infx.jpg","herpes zoster","infx","No hint"],
["herpes zoster_2_infx.jpg","herpes zoster","infx","No hint"],
["herpes zoster_infx.jpg","herpes zoster","infx","No hint"],
["herpetic whitlow$an adventurous finger$_infx.jpg","herpetic whitlow","infx","an adventurous finger"],
["hidradenitis suppurativa_inflam.jpg","hidradenitis suppurativa","infl","No hint"],
["hidradenitis suppurativa__inflam.jpg","hidradenitis suppurativa","infl","No hint"],
["hypertrophic lichen planus_infl.jpg","hypertrophic lichen planus","infl","No hint"],
["hypertrophic lichen planus__infl.jpg","hypertrophic lichen planus","infl","No hint"],
["ichthyosis vulgaris$genetic$_gene.jpg","ichthyosis vulgaris","gene","genetic"],
["ichthyosis vulgaris$genetic, common$_gene.jpg","ichthyosis vulgaris","gene","genetic, common"],
["ichthyosis vulgaris_gene.jpg","ichthyosis vulgaris","gene","No hint"],
["ILVEN$Blaschko$_neo","ILVEN","neo","Blaschko"],
["impetigo$collarette of scale$_infx.jpg","impetigo","infx","collarette of scale"],
["impetigo_infx.jpg","impetigo","infx","No hint"],
["impetigo__infx.jpg","impetigo","infx","No hint"],
["inverse pityriasis rosea$possibly associated with HHV-6 or 7$_other.jpg","inverse pityriasis rosea","other","possibly associated with HHV-6 or 7"],
["inverse psoriasis$inflammatory cause of intertrigo$_infl.jpg","inverse psoriasis","infl","inflammatory cause of intertrigo"],
["inverse psoriasis$not tinea$_infl.jpg","inverse psoriasis","infl","not tinea"],
["juvenile spring eruption$characteristic location, in boys, in spring$_1infl.jpg","juvenile spring eruption","infl","characteristic location, in boys, in spring"],
["juvenile spring eruption$characteristic location, in boys, in spring$_infl.jpg","juvenile spring eruption","infl","characteristic location, in boys, in spring"],
["juvenile xanthogranuloma$may be seen with NF1 and JMML$_b_neo.png","juvenile xanthogranuloma","neo","may be seen with NF1 and JMML"],
["juvenile xanthogranulomas with skin and eye involvement$foamy$_b_neo","juvenile xanthogranulomas with skin and eye involvement","neo","foamy"],
["Kaposi's sarcoma$neoplastic$_1_neo.jpg","Kaposi's sarcoma","neo","neoplastic"],
["Kaposi's sarcoma$neoplastic$_neo.jpg","Kaposi's sarcoma","neo","neoplastic"],
["keloids$scarring$_neo.jpg","keloids","neo","scarring"],
["keloids_neo.jpg","keloids","neo","No hint"],
["keratoderma blenorrhagicum in Reiter's syndrome$1 month after onset of arthritis$_infl.jpg","keratoderma blenorrhagicum in Reiter's syndrome","infl","1 month after onset of arthritis"],
["keratosis pilaris atrophicans faciei (ulerythema ophryogenes)$KP subtype, starts on lateral eyebrows$_infl","keratosis pilaris atrophicans faciei (ulerythema ophryogenes)","infl","KP subtype, starts on lateral eyebrows"],
["koala.png","koala.png","","No hint"],
["Langerhans cell histiocytosis$neoplastic$_neo.jpg","Langerhans cell histiocytosis","neo","neoplastic"],
["Langerhans cell histiocytosis_neo.jpg","Langerhans cell histiocytosis","neo","No hint"],
["large plaque parapsoriasis$para$_infl.jpg","large plaque parapsoriasis","infl","para"],
["leiomyomas$neoplastic, connective tissue origin$_neo.jpg","leiomyomas","neo","neoplastic, connective tissue origin"],
["leukemia cutis (AML)_neo.jpg","leukemia cutis (AML)","neo","No hint"],
["leukoplakia$general term for this$_neo.jpg","leukoplakia","neo","general term for this"],
["lichen planus annulare_infl.jpg","lichen planus annulare","infl","No hint"],
["lichen planus pigmentosus_infl.jpg","lichen planus pigmentosus","infl","No hint"],
["lichen planus$inflammatory$_infl.jpg","lichen planus","infl","inflammatory"],
["lichen planus$interface dermatitis$_infl.jpg","lichen planus","infl","interface dermatitis"],
["lichen planus$often features more scale$_infl.jpg","lichen planus","infl","often features more scale"],
["lichen sclerosus et atrophicus_1_inflam.jpg","lichen sclerosus et atrophicus","infl","No hint"],
["lichen sclerosus et atrophicus_2_inflam.jpg","lichen sclerosus et atrophicus","infl","No hint"],
["lichen sclerosus et atrophicus_inflam.jpg","lichen sclerosus et atrophicus","infl","No hint"],
["lichen sclerosus et atrophicus__inflam.jpg","lichen sclerosus et atrophicus","infl","No hint"],
["linear morphea en coup de sabre$inflammatory$_infl.jpg","linear morphea en coup de sabre","infl","inflammatory"],
["lipodermatosclerosis_inflam.jpg","lipodermatosclerosis","infl","No hint"],
["lupus miliaris disseminatus faciei$not acne$_infl.jpg","lupus miliaris disseminatus faciei","infl","not acne"],
["lupus miliaris disseminatus faciei$rosacea-related condition$_infl.jpg","lupus miliaris disseminatus faciei","infl","rosacea-related condition"],
["lymphangioma circuscriptum_neo.jpg","lymphangioma circuscriptum","neo","No hint"],
["lymphocytic infiltrate of Jessner$lymphocytic$_inflam.jpg","lymphocytic infiltrate of Jessner","infl","lymphocytic"],
["lymphocytic infiltrate of Jessner_inflam.jpg","lymphocytic infiltrate of Jessner","infl","No hint"],
["Madura foot (Actinomycoses spp)$yellow granules$_infx.jpg","Madura foot (Actinomycoses spp)","infx","yellow granules"],
["mastocytoma$blisters$_neo.jpg","mastocytoma","neo","blisters"],
["mastocytoma$may have Darier sign$_neo.jpg","mastocytoma","neo","may have Darier sign"],
["melanoma$bad$_neo.jpg","melanoma","neo","bad"],
["melanoma$don't let that one walk out the door$_neo.jpg","melanoma","neo","don't let that one walk out the door"],
["melanoma_1neo.jpg","melanoma","neo","No hint"],
["melanoma_neo.jpg","melanoma","neo","No hint"],
["metastases (lung)$neoplastic, nonspecific$_neo.jpg","metastases (lung)","neo","neoplastic, nonspecific"],
["molluscum contagiosum$viral$_1infx.jpg","molluscum contagiosum","infx","viral"],
["molluscum contagiosum$viral$_infx.jpg","molluscum contagiosum","infx","viral"],
["morbilliform rash (EBV)_infx.jpg","morbilliform rash (EBV)","infx","No hint"],
["morphea$inflammation at periphery$_infl.jpg","morphea","infl","inflammation at periphery"],
["morphea$inflammatory border$_infl.jpg","morphea","infl","inflammatory border"],
["mycosis fungoides$classic distribution$_neo.jpg","mycosis fungoides","neo","classic distribution"],
["mycosis fungoides$lymphoproliferative$_neo.jpg","mycosis fungoides","neo","lymphoproliferative"],
["mycosis fungoides$neoplastic$_1_neo.jpg","mycosis fungoides","neo","neoplastic"],
["mycosis fungoides$neoplastic$_neo.jpg","mycosis fungoides","neo","neoplastic"],
["nail clubbing (in a patient with lung cancer)_other.jpg","nail clubbing (in a patient with lung cancer)","other","No hint"],
["nail clubbing_other.jpg","nail clubbing","other","No hint"],
["necrobiosis lipoidica$classic location and appearance$_infl.jpg","necrobiosis lipoidica","infl","classic location and appearance"],
["necrotic ulcer, wide differential, here with CD8+ CTCL_neo.jpg","necrotic ulcer, wide differential, here with CD8+ CTCL","neo","No hint"],
["neurofibromatosis$autosomal dominant$_gene.jpg","neurofibromatosis","gene","autosomal dominant"],
["neurofibromatosis$von Recklinghausen's$_gene.jpg","neurofibromatosis","gene","von Recklinghausen's"],
["nevus of Ota$melanin$_other.jpg","nevus of Ota","other","melanin"],
["nevus sebaceous (of Jadasshon)$congenital$_neo.jpg","nevus sebaceous (of Jadasshon)","neo","congenital"],
["nevus sebaceous_neo.jpg","nevus sebaceous","neo","No hint"],
["onychogryphosis_otherhn.jpg","onychogryphosis","otherhn","No hint"],
["onychomycosis_infx.jpg","onychomycosis","infx","No hint"],
["orf$no treatment needed, viral$_infx.jpg","orf","infx","no treatment needed, viral"],
["orf$viral$_infx.jpg","orf","infx","viral"],
["pagetoid reticulosis (Woringer Kolopp disease)$neoplastic$_b_neo","pagetoid reticulosis (Woringer Kolopp disease)","neo","neoplastic"],
["paronychia$may be seen with kinase inhibitor or actiretin use$_infx.jpg","paronychia","infx","may be seen with kinase inhibitor or actiretin use"],
["parvovirus B19, erythema infectiosum$also known as fifth disease$_infx.jpg","parvovirus B19, erythema infectiosum","infx","also known as fifth disease"],
["pellagra$nutritional$_other.png","pellagra","other","nutritional"],
["pellagra$photo-distributed$_other.jpg","pellagra","other","photo-distributed"],
["pemphigus vulgaris$bullous$_infl.jpg","pemphigus vulgaris","infl","bullous"],
["pemphigus vulgaris$desmoglein$_infl.jpg","pemphigus vulgaris","infl","desmoglein"],
["pemphigus vulgaris$immunobullous$_infl.jpg","pemphigus vulgaris","infl","immunobullous"],
["pemphigus vulgaris$not infectious$_infl.jpg","pemphigus vulgaris","infl","not infectious"],
["perioral dermatitis$steroid use$_inflam.jpg","perioral dermatitis","infl","steroid use"],
["perioral dermatitis_inflam.jpg","perioral dermatitis","infl","No hint"],
["Peutz-Jeghers$hamartamous intestinal polyps$_gene.jpg","Peutz-Jeghers","gene","hamartamous intestinal polyps"],
["piezogenic papules$normal variant$_other.jpg","piezogenic papules","other","normal variant"],
["piezogenic papules_other.jpg","piezogenic papules","other","No hint"],
["pigmented purpuric dermatosis (capillaritis)_infl.jpg","pigmented purpuric dermatosis (capillaritis)","infl","No hint"],
["pitted keratolysis$Cornebacterium minutissumum$_infx.jpg","pitted keratolysis","infx","Cornebacterium minutissumum"],
["pityriasis amiantacea$give a general term for this morphology, may be secondary to e.g. psoriasis, seborrheic dermatitis, or tinea capitis$_other.jpg","pityriasis amiantacea","other","give a general term for this morphology, may be secondary to e.g. psoriasis, seborrheic dermatitis, or tinea capitis"],
["pityriasis lichenoides chronica$present for months to years$_infl.jpg","pityriasis lichenoides chronica","infl","present for months to years"],
["pityriasis rosea$trailing scale$_infl.jpg","pityriasis rosea","infl","trailing scale"],
["pityriasis rosea_1_other.jpg","pityriasis rosea","other","No hint"],
["pityriasis rosea_2_other.jpg","pityriasis rosea","other","No hint"],
["pityriasis rosea_other.jpg","pityriasis rosea","other","No hint"],
["pityriasis rubra pilaris$erythrodermic$_infl.jpg","pityriasis rubra pilaris","infl","erythrodermic"],
["pityriasis rubra pilaris$islands$_infl.jpg","pityriasis rubra pilaris","infl","islands"],
["pityriasis versicolor_infx.jpg","pityriasis versicolor","infx","No hint"],
["pityrosporum folliculitis$fungal folliculitis$_infx.jpg","pityrosporum folliculitis","infx","fungal folliculitis"],
["plane warts$viral$_b_infx.png.jpg","plane warts","infx","viral"],
["plane warts$viral$_infx.png","plane warts","infx","viral"],
["plane warts_infx.jpg","plane warts","infx","No hint"],
["plane xanthoma$associated with multiple myeloma and monoclonal gammopathy$_other.png","plane xanthoma","other","associated with multiple myeloma and monoclonal gammopathy"],
["plaque parapsoriasis$not mycosis fungoides, but perhaps related$_other.jpg","plaque parapsoriasis","other","not mycosis fungoides, but perhaps related"],
["polymorphous light eruption$after a trip to the park in May$_inflam.jpg","polymorphous light eruption","infl","after a trip to the park in May"],
["porokeratosis of Mibelli_neo.jpg","porokeratosis of Mibelli","neo","No hint"],
["port-wine stain (in Sturge-Weber syndrome)_neo","port-wine stain (in Sturge-Weber syndrome)","neo","No hint"],
["primary syphilis$indurated$_infx","primary syphilis","infx","indurated"],
["pruritic urticarial papules and plaques of pregnancy (PUPPP) with erythema of abdominal striae$itchy$_infl.jpg","pruritic urticarial papules and plaques of pregnancy (PUPPP) with erythema of abdominal striae","infl","itchy"],
["pseudofolliculitis barbae$razor burn$_infl.jpg","pseudofolliculitis barbae","infl","razor burn"],
["pseudofolliculitis barbae$shaving-related$_infl.jpg","pseudofolliculitis barbae","infl","shaving-related"],
["psoriasis and zoster$two conditions$_other.jpg","psoriasis and zoster","other","two conditions"],
["psoriasis of scalp_infl.jpg","psoriasis of scalp","infl","No hint"],
["psoriasis vulgaris_infl.jpg","psoriasis vulgaris","infl","No hint"],
["psoriasis$classic location$_infl.jpg","psoriasis","infl","classic location"],
["psoriasis$common$_1_infl.jpg","psoriasis","infl","common"],
["psoriasis$common$_infl.jpg","psoriasis","infl","common"],
["psoriasis_1_infl.jpg","psoriasis","infl","No hint"],
["psoriasis_infl.jpg","psoriasis","infl","No hint"],
["psoriatic nails (oil spots, onycholysis)_1_infl.jpg","psoriatic nails (oil spots, onycholysis)","infl","No hint"],
["psoriatic nails (oil spots, onycholysis)_inflam.jpg","psoriatic nails (oil spots, onycholysis)","infl","No hint"],
["pustular psoriasis$inflammatory$_infl.jpg","pustular psoriasis","infl","inflammatory"],
["pustular psoriasis$large Munro microabscesses$_infl.jpg","pustular psoriasis","infl","large Munro microabscesses"],
["pustular psoriasis$you might reach for cyclosporine$_infl.jpg","pustular psoriasis","infl","you might reach for cyclosporine"],
["pyogenic granuloma$vascular$_neo.jpg","pyogenic granuloma","neo","vascular"],
["Reiter's disease$with urethritis, conjunctivitis, and arthritis$_infl.jpg","Reiter's disease","infl","with urethritis, conjunctivitis, and arthritis"],
["Reiter's syndrome$not psoriasis$_1other.jpg","Reiter's syndrome","other","not psoriasis"],
["rhinoscleroma (Klebsiella rhinoscleromatis)$caused by Klebsiella subtype$_infx.png","rhinoscleroma (Klebsiella rhinoscleromatis)","infx","caused by Klebsiella subtype"],
["rosacea$common$_infl.jpg","rosacea","infl","common"],
["rosacea$no comedones$_infl.jpg","rosacea","infl","no comedones"],
["Rothmund-Thomson syndrome$RECQL4 gene, rash on cheeks, juvenile cataracts, early poikiloderma$_gene","Rothmund-Thomson syndrome","gene","RECQL4 gene, rash on cheeks, juvenile cataracts, early poikiloderma"],
["sarcoidosis$annular differential$_infl.png","sarcoidosis","infl","annular differential"],
["scabies$itchy$_infx.jpg","scabies","infx","itchy"],
["scabies$mineral oil prep$_infx.png","scabies","infx","mineral oil prep"],
["scabies_1_infx.jpg","scabies","infx","No hint"],
["scabies_infx.jpg","scabies","infx","No hint"],
["scabies__infx.jpg","scabies","infx","No hint"],
["scabies___infx.jpg","scabies","infx","No hint"],
["scale, black dots in tinea capitis$infectious$_infx.png","scale, black dots in tinea capitis","infx","infectious"],
["SCCIS (Bowen's disease)$premalignant$_neo (2).jpg","SCCIS (Bowen's disease)","neo","premalignant"],
["SCCIS (Bowen's disease)$premalignant$_neo.jpg","SCCIS (Bowen's disease)","neo","premalignant"],
["schistosomiasis, parasitic flatworms $snail fever$.png","schistosomiasis, parasitic flatworms ","","snail fever"],
["sclerodactyly in scleroderma_infl.png","sclerodactyly in scleroderma","infl","No hint"],
["scleroderma$rheumatologic$_1_infl.jpg","scleroderma","infl","rheumatologic"],
["scleroderma$rheumatologic$_infl.jpg","scleroderma","infl","rheumatologic"],
["scleroderma$salt and pepper dyspigmentation$_infl","scleroderma","infl","salt and pepper dyspigmentation"],
["scleromyxedema$fibroblast hyperplasia$_other.png","scleromyxedema","other","fibroblast hyperplasia"],
["SCLE_inflam.jpg","SCLE","infl","No hint"],
["scrofuloderma$mycobacterial$_infx.png","scrofuloderma","infx","mycobacterial"],
["scrotal calcinosis_neo.jpg","scrotal calcinosis","neo","No hint"],
["scrotal cysts_1_neo.jpg","scrotal cysts","neo","No hint"],
["scrotal cysts_neo.jpg","scrotal cysts","neo","No hint"],
["seabeceous gland hyperplasia_neo","seabeceous gland hyperplasia","neo","No hint"],
["sebaceous gland hyperplasia_1_neo","sebaceous gland hyperplasia","neo","No hint"],
["seborrheic dermatitis$inferior picture is infant$_infl.png","seborrheic dermatitis","infl","inferior picture is infant"],
["seborrheic dermatitis$inferior picture with petaloid variant$_infl.png","seborrheic dermatitis","infl","inferior picture with petaloid variant"],
["seborrheic dermatitis$inflammatory$_infl.jpg","seborrheic dermatitis","infl","inflammatory"],
["seborrheic dermatitis$polycyclic petaloid variant in superior image$_infl.png","seborrheic dermatitis","infl","polycyclic petaloid variant in superior image"],
["seborrheic dermatitis_1_inflam.jpg","seborrheic dermatitis","infl","No hint"],
["seborrheic dermatitis_infl.png","seborrheic dermatitis","infl","No hint"],
["seborrheic dermatitis_inflam.jpg","seborrheic dermatitis","infl","No hint"],
["seborrheic dermatitis_z_infl.png","seborrheic dermatitis","infl","No hint"],
["seborrheic keratoses_1_neo.jpg","seborrheic keratoses","neo","No hint"],
["seborrheic keratoses_neo.jpg","seborrheic keratoses","neo","No hint"],
["seborrheic keratosis_neo.jpg","seborrheic keratosis","neo","No hint"],
["secondary syphilis$bacterial$_infx.jpg","secondary syphilis","infx","bacterial"],
["secondary syphilis$infectious$_infx.jpg.png","secondary syphilis","infx","infectious"],
["secondary syphilis, corymiform (flower-like) lesion, mucous patch on tongue, historical images of secondary syphilis lesions_infx.png","secondary syphilis, corymiform (flower-like) lesion, mucous patch on tongue, historical images of secondary syphilis lesions","infx","No hint"],
["SJS-TEN$drug reaction$_1other.jpg","SJS-TEN","other","drug reaction"],
["SJS-TEN$drug reaction$_other.jpg","SJS-TEN","other","drug reaction"],
["SJS-TEN_other.jpg","SJS-TEN","other","No hint"],
["smallpox$viral$_infx.jpg","smallpox","infx","viral"],
["spider bite$Charlotte$_infx.jpg","spider bite","infx","Charlotte"],
["spiradenoma$eosinophilic hyaline deposits among tumor cells$_neo.png","spiradenoma","neo","eosinophilic hyaline deposits among tumor cells"],
["squamous cell carcinoma (spindle cell by histologic description)$spindle cells, vimentin positive but AE1 and AE3 positive, p63 positive, CK903 positive$_neo","squamous cell carcinoma (spindle cell by histologic description)","neo","spindle cells, vimentin positive but AE1 and AE3 positive, p63 positive, CK903 positive"],
["squamous cell carcinoma in situ$neoplastic$_neo.jpg","squamous cell carcinoma in situ","neo","neoplastic"],
["squamous cell carcinoma$CK5 and CK6 positive$_neo","squamous cell carcinoma","neo","CK5 and CK6 positive"],
["squamous cell carcinoma$cytokeratin AE1 and AE3 positive$_neo","squamous cell carcinoma","neo","cytokeratin AE1 and AE3 positive"],
["squamous cell carcinoma$cytokeratins AE1 and AE3 positive, cytokeratins 5 and 6 also positive$_neo","squamous cell carcinoma","neo","cytokeratins AE1 and AE3 positive, cytokeratins 5 and 6 also positive"],
["squamous cell carcinoma$epithelial membrane antigen (EMA) positive, Ber-EP4 negative$_neo","squamous cell carcinoma","neo","epithelial membrane antigen (EMA) positive, Ber-EP4 negative"],
["squamous cell carcinoma$from sun exposure$_neo.jpg","squamous cell carcinoma","neo","from sun exposure"],
["squamous cell carcinoma$increased risk with voriconazole and vemurafenib$_neo.jpg","squamous cell carcinoma","neo","increased risk with voriconazole and vemurafenib"],
["squamous cell carcinoma$neoplastic$_neo.jpg","squamous cell carcinoma","neo","neoplastic"],
["squamous cell carcinoma$UV exposure$_neo.jpg","squamous cell carcinoma","neo","UV exposure"],
["squamous cell carcinoma$UV-exposure$_neo.jpg","squamous cell carcinoma","neo","UV-exposure"],
["squamous cell carcinoma_1_neo.jpg","squamous cell carcinoma","neo","No hint"],
["squamous cell carcinoma_neo.jpg","squamous cell carcinoma","neo","No hint"],
["steatocystoma multiplex$KRT17$_gene.png","steatocystoma multiplex","gene","KRT17"],
["striae in Cushing's syndrome (prolonged steroids vs endocrine tumor)$endocrinologic$_other.jpg","striae in Cushing's syndrome (prolonged steroids vs endocrine tumor)","other","endocrinologic"],
["subacute cutaneous lupus erythematosus$after terbinafine or thiazide use$_infl.jpg","subacute cutaneous lupus erythematosus","infl","after terbinafine or thiazide use"],
["subcorneal pustular dermatosis (Sneddon-Wilkinson)$give 2 names$_infl.png","subcorneal pustular dermatosis (Sneddon-Wilkinson)","infl","give 2 names"],
["subcorneal pustular dermatosis$dapsone often effective$_infl.png","subcorneal pustular dermatosis","infl","dapsone often effective"],
["subcutaneous fat necrosis of the newborn$unclear etiology, may be secondary to hypothermia, hypoxia, fetal stress, other$_other.png","subcutaneous fat necrosis of the newborn","other","unclear etiology, may be secondary to hypothermia, hypoxia, fetal stress, other"],
["sunburn!_infl.jpg","sunburn!","infl","No hint"],
["Sweet's syndrome$juicy$_infl","Sweet's syndrome","infl","juicy"],
["Sweet's syndrome$juicy$_infl.jpg","Sweet's syndrome","infl","juicy"],
["Sweet's syndrome$may have ALL$_infl","Sweet's syndrome","infl","may have ALL"],
["Sweet's syndrome$non-infectious$_infl.jpg","Sweet's syndrome","infl","non-infectious"],
["Sweet's syndrome$steroid-responsive$_infl.png","Sweet's syndrome","infl","steroid-responsive"],
["Sweet's syndrome_1_infl.png","Sweet's syndrome","infl","No hint"],
["Sweet's syndrome_infl.jpg.png","Sweet's syndrome","infl","No hint"],
["sycosis barbae (usually Staphylococcus)_infx.jpg","sycosis barbae (usually Staphylococcus)","infx","No hint"],
["syphilis$indurated$_infx.jpg","syphilis","infx","indurated"],
["syphilitic gummas, tertiary syphilis$penicillin$_infx.png","syphilitic gummas, tertiary syphilis","infx","penicillin"],
["syringocystadenoma papilliferum$slide$_neo.png","syringocystadenoma papilliferum","neo","slide"],
["syringomas$classic location$_neo","syringomas","neo","classic location"],
["syringomas$paisley$_neo","syringomas","neo","paisley"],
["syringomas$related to sweat glands$_neo","syringomas","neo","related to sweat glands"],
["syringomas_neo","syringomas","neo","No hint"],
["telangiectasia macularis eruptiva perstans (type of mastocytosis)$fried egg appearance$_neo.png","telangiectasia macularis eruptiva perstans (type of mastocytosis)","neo","fried egg appearance"],
["terra firma_other.jpg","terra firma","other","No hint"],
["tick_infx.png","tick","infx","No hint"],
["tinea axillaris_infx.jpg","tinea axillaris","infx","No hint"],
["tinea capitis$infectious$_infx.png","tinea capitis","infx","infectious"],
["tinea corporis$common$_infx.jpg","tinea corporis","infx","common"],
["tinea corporis$infectious$_1_infx.png","tinea corporis","infx","infectious"],
["tinea corporis$infectious$_infx.png","tinea corporis","infx","infectious"],
["tinea corporis$not uncommon$_infx.jpg","tinea corporis","infx","not uncommon"],
["tinea corporis$scrape scrape scraperoo$_infx.jpg","tinea corporis","infx","scrape scrape scraperoo"],
["tinea corporis$subtly obvious$_infx.jpg","tinea corporis","infx","subtly obvious"],
["tinea corporis_infx.jpg.png","tinea corporis","infx","No hint"],
["tinea cruris$common$_infx.jpg","tinea cruris","infx","common"],
["tinea cruris$infectious$_infx.png","tinea cruris","infx","infectious"],
["tinea cruris$scale$_infx.png","tinea cruris","infx","scale"],
["tinea facei_b_infx.png","tinea facei","infx","No hint"],
["tinea facei_infx","tinea facei","infx","No hint"],
["tinea faciale_1_infx.jpg","tinea faciale","infx","No hint"],
["tinea faciale_2_infx.jpg","tinea faciale","infx","No hint"],
["tinea faciale_infx.jpg","tinea faciale","infx","No hint"],
["tinea faciei_infx.jpg","tinea faciei","infx","No hint"],
["tinea incognito$has been treating$_infx.jpg","tinea incognito","infx","has been treating"],
["tinea manuum$infectious$_infx","tinea manuum","infx","infectious"],
["Tinea nigra#Hortaea werneckii#_infx","Tinea nigra#Hortaea werneckii#","infx","No hint"],
["tinea nigra$fungal$_infx.png","tinea nigra","infx","fungal"],
["tinea nigra$Hortaea werneckii$_infx.png","tinea nigra","infx","Hortaea werneckii"],
["tinea on hand and buttocks_infx.jpg","tinea on hand and buttocks","infx","No hint"],
["tinea pedis$maceration, moist and warm environment$_infx.jpg","tinea pedis","infx","maceration, moist and warm environment"],
["tinea pedis$mocassin$_infx.jpg","tinea pedis","infx","mocassin"],
["tinea pedis_1_infx.jpg","tinea pedis","infx","No hint"],
["tinea pedis_2_infx.jpg","tinea pedis","infx","No hint"],
["tinea pedis_infx.jpg","tinea pedis","infx","No hint"],
["tinea versicolor_1_infx.jpg","tinea versicolor","infx","No hint"],
["tinea versicolor_2_infx.jpg","tinea versicolor","infx","No hint"],
["tinea versicolor_infx.jpg","tinea versicolor","infx","No hint"],
["torus palatinus$name for central hump on palate$_other","torus palatinus","other","name for central hump on palate"],
["trichilemmal (pilar) cyst_neo.png","trichilemmal (pilar) cyst","neo","No hint"],
["trichilemomma$glycogen, may arise from outer-root sheath$_neo.png","trichilemomma","neo","glycogen, may arise from outer-root sheath"],
["trichoadenoma$lining of benign infundibulum-like squamous epithelium$_neo.png","trichoadenoma","neo","lining of benign infundibulum-like squamous epithelium"],
["trichofolliculoma$babies$_neo.png","trichofolliculoma","neo","babies"],
["trichomycosis axillaris (Corynebacterium species)$not a real mycosis$_infx.jpg","trichomycosis axillaris (Corynebacterium species)","infx","not a real mycosis"],
["trichomycosis axillaris (Corynebacterium species)_infx.jpg","trichomycosis axillaris (Corynebacterium species)","infx","No hint"],
["trichostasis spinulosa$follicular plugs$_other.png","trichostasis spinulosa","other","follicular plugs"],
["trichotillomania with trichobezoar (hairball formed after ingestion)$hair$_other.png","trichotillomania with trichobezoar (hairball formed after ingestion)","other","hair"],
["Tropical ulcer, also called tropical phagedenic ('gnawed') ulcer$traumatized, polymicrobial infection, lower legs, in tropics$_infx","Tropical ulcer, also called tropical phagedenic ('gnawed') ulcer","infx","traumatized, polymicrobial infection, lower legs, in tropics"],
["tuberculosis verrucosa cutis (TB inoculation into previously sensitized person with moderate immunity)$prosector's wart$_infx.png","tuberculosis verrucosa cutis (TB inoculation into previously sensitized person with moderate immunity)","infx","prosector's wart"],
["tuberous xanthomas in familial hypercholesterolemia (relatively common among related conditions)$mutation usually in LDLR or APOB, whose protein products interact$_b_gene","tuberous xanthomas in familial hypercholesterolemia (relatively common among related conditions)","gene","mutation usually in LDLR or APOB, whose protein products interact"],
["tuberous xanthomas$lipid$_b_gene.png","tuberous xanthomas","gene","lipid"],
["tungiasis (tunga penetrans, the chigoe flea)$tropical$_infx.png","tungiasis (tunga penetrans, the chigoe flea)","infx","tropical"],
["tungiasis$an infestation$_infx.png","tungiasis","infx","an infestation"],
["urticaria pigmentosa (form of mastocytosis)$check tryptase$_neo.jpg","urticaria pigmentosa (form of mastocytosis)","neo","check tryptase"],
["urticaria with dermatographism$see linear lesions above waistband$_infl.jpg","urticaria with dermatographism","infl","see linear lesions above waistband"],
["urticaria$itchy$_infl.jpg","urticaria","infl","itchy"],
["urticaria$itchy, transient$_infl.jpg","urticaria","infl","itchy, transient"],
["urticaria$pruritus$_infl.jpg","urticaria","infl","pruritus"],
["urticarial vasculitis$painful$_infl.jpg","urticarial vasculitis","infl","painful"],
["urticaria_infl.jpg","urticaria","infl","No hint"],
["varicella$dew drop$_infx.jpg.png","varicella","infx","dew drop"],
["varicella$itchy$_b_infx.jpg","varicella","infx","itchy"],
["varicella$viral$_infx.jpg","varicella","infx","viral"],
["viral exanthem (erythema infectiosum)$focus on the rash$_infx.jpg","viral exanthem (erythema infectiosum)","infx","focus on the rash"],
["vitiligo_1_infl.jpg","vitiligo","infl","No hint"],
["vitiligo_2_infl.jpg","vitiligo","infl","No hint"],
["vitiligo_3_infl.jpg","vitiligo","infl","No hint"],
["vitiligo_infl.jpg","vitiligo","infl","No hint"],
["warts_1_infx.jpg","warts","infx","No hint"],
["warts_infx.jpg","warts","infx","No hint"],
["wart_b_infx.png","wart","infx","No hint"],
["wart__infx.jpg","wart","infx","No hint"],
["wart___infx.jpg","wart","infx","No hint"],
["Well's syndrome (eosinophilic cellulitis)$well treat it with steroids$_b_other","Well's syndrome (eosinophilic cellulitis)","other","well treat it with steroids"],
["wide differential, here with CD8+ CTCL_neo.jpg","wide differential, here with CD8+ CTCL","neo","No hint"],
["X-linked ichthyosis_$affects males$_gene.jpg","X-linked ichthyosis","gene","affects males"],
["X-linked ichthyosis_$type of ichthyosis$_gene.jpg","X-linked ichthyosis","gene","type of ichthyosis"],
["xanthelasma palpebrum$may or may not have hyperlipidemia$_neo","xanthelasma palpebrum","neo","may or may not have hyperlipidemia"],
["xanthelasma palpebrum_other","xanthelasma palpebrum","other","No hint"],
["xanthomas_other.jpg","xanthomas","other","No hint"],
["xeroderma pigmentosum$early skin cancers$_b_gene","xeroderma pigmentosum","gene","early skin cancers"],
["xeroderma pigmentosum$NER$_b_gene","xeroderma pigmentosum","gene","NER"],
["Zoon's balanitis$plasma cells$_b_other","Zoon's balanitis","other","plasma cells"],
["zoster$it's a bird, it's a plane, it's...$herpes zoster_infx.jpg","zoster","infx","it's a bird, it's a plane, it's..."],
["zoster$left side of face unaffected$_infx.jpg","zoster","infx","left side of face unaffected"],
["zoster_infx.jpg","zoster","infx","No hint"],

 ];